# Generated by Django 4.1.7 on 2023-04-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_rename_teammembers_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='desc',
            new_name='teamdesc',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='img',
            new_name='teamimg',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='teamname',
        ),
    ]
