# Generated by Django 4.1.7 on 2023-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memname', models.CharField(max_length=250)),
                ('memimg', models.ImageField(upload_to='pics')),
                ('memdesc', models.TextField()),
            ],
        ),
    ]
